### ISSUE TITLE
[Feature] Chance for Amethyst level upgrades?

### ISSUE THREAD

**Issue by madheadltd** [Aton-Kish/reinforced-chests#15]
### Describe the solution you'd like

Using amethyst to upgrade diamond tier storage, like amethyst chest, barrel, and shulker box? This will require new texture tho.

### Additional context

1. I noticed that the texture of double chest is basically stretched from single chest, possible remaking the texture to fit the style?
2. Possible for extra 'reinforced' storage-related items/blocks? For examples, bundles(+stacks), hoppers(speed/filter/multiple filters)? 
3. Options to upgrade furnace, smoker, and blasting furnace to increase their smelting speeds? (maybe not much related to storage system)
4. Isn't it more suitable to use a pickaxe to break these metal-upgraded storage blocks? Currently using an axe to break it.

**Comment by Aton-Kish** [comment]
Thank you for your feature request.
However, I'm not going to add this feature to the main road currently because I respect vanilla.
Amethyst is a new item, so I don't know if it is more valuable than diamonds.
It feels like a gem such as an emerald or a lapis lazuli, or it feels like a glowstone.
I'd like to consider it when I'll understand the value of amethysts.

By the way,
1. It is possible to customize the texture, but it is quite difficult to make it look satisfactory.
2. I don't think about them for now. I'll make them if I want.
3. I think it's possible, but it's not in my concept currently.
4. This may be true. It may change in the future. (thanks!)

**Comment by madheadltd** [comment]
> Thank you for your feature request. However, I'm not going to add this feature to the main road currently because I respect vanilla. Amethyst is a new item, so I don't know if it is more valuable than diamonds. It feels like a gem such as an emerald or a lapis lazuli, or it feels like a glowstone. I'd like to consider it when I'll understand the value of amethysts.
> 
> By the way,
> 
> 1. It is possible to customize the texture, but it is quite difficult to make it look satisfactory.
> 2. I don't think about them for now. I'll make them if I want.
> 3. I think it's possible, but it's not in my concept currently.
> 4. This may be true. It may change in the future. (thanks!)

Thank you for your reply and your hard work, please feel no pressure on any suggestions of progress about this mod.

**Comment by madheadltd** [comment]
> Thank you for your feature request. However, I'm not going to add this feature to the main road currently because I respect vanilla. Amethyst is a new item, so I don't know if it is more valuable than diamonds. It feels like a gem such as an emerald or a lapis lazuli, or it feels like a glowstone. I'd like to consider it when I'll understand the value of amethysts.
> 
> By the way,
> 
> 1. It is possible to customize the texture, but it is quite difficult to make it look satisfactory.
> 2. I don't think about them for now. I'll make them if I want.
> 3. I think it's possible, but it's not in my concept currently.
> 4. This may be true. It may change in the future. (thanks!)

Thank you for your reply and your hard work, please feel no pressure on any suggestions of progress about this mod.
